site_name: Moodle Data Archiving Concept
site_url: http://localhost/
repo_url: https://github.com/ngandrass/moodle-data-archiving-concept
edit_uri: edit/master/docs/

copyright: "Copyright &copy; 2024 Niels Gandraß<br>License: GNU General Public License v3.0"

extra:
  social:
    - icon: simple/moodle
      link: https://moodle.org/plugins/quiz_archiver
      name: "Moodle Plugin Directory: quiz_archiver"
    - icon: fontawesome/brands/github
      link: https://github.com/ngandrass/moodle-quiz_archiver
      name: "GitHub: moodle-quiz_archiver"
    - icon: fontawesome/brands/github
      link: https://github.com/ngandrass/moodle-quiz-archive-worker
      name: "GitHub: moodle-quiz-archive-worker"
  demand_mandatory: "<span style='float:right; font-weight: 400;'>Mandatory <span style='color:#C62828;'>:material-alert:</span></span>"
  demand_high: "<span style='float:right; font-weight: 400;'>High Demand <span style='color:#FF5722;'>:material-circle:</span></span>"
  demand_medium: "<span style='float:right; font-weight: 400;'>Medium Demand <span style='color:#FFC107;'>:material-circle:</span></span>"
  demand_low: "<span style='float:right; font-weight: 400;'>Basic Demand <span style='color:#689F38;'>:material-circle:</span></span>"
  moodle_component_manager: "local_archive"
  todo: "{== **TODO** ==}"

#   version:
#     provider: mike

plugins:
  # - mike
  - drawio
  - glightbox:
      shadow: true
  - macros
  - panzoom:
      key: "shift"
  - search
  - social

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.code.copy
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - search.suggest
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - css/extra.css

nav:
  - "Introduction": index.md
  - "Changelog": changelog.md

  - "Analysis":
      - analysis/index.md
      - "Existing Solutions": analysis/existingsolutions.md
      - "Data Analysis": analysis/data-analysis.md

  - "Requirements":
    - requirements/index.md
    - "User Stories": requirements/user-stories.md
    - "Base Requirements": requirements/base-requirements.md

  - "Architecture":
    - architecture/index.md
    - "Components":
      - architecture/components/archiving-manager.md
      - architecture/components/activity-archiving-drivers.md
      - architecture/components/worker-services.md
      - architecture/components/storage-drivers.md
      - architecture/components/external-event-connectors.md
    - "Interfaces (APIs) and Signals":
      - architecture/interfaces/archive-job-states.md
      - architecture/interfaces/events.md
      - architecture/interfaces/activity-archiving-drivers.md
      - architecture/interfaces/storage-drivers.md
